---
title: "01_Iteration_protocol"
output: html_document
---

[Contenido](../Contents.Rmd) \| [Anterior (5.2 Técnicas de encapsulación)](../05_Object_model/02_Classes_encapsulation.Rmd) \| [Próximo (6.2 Personalización de la iteración con generadores)](02_Customizing_iteration.Rmd)

### 6.1 Protocolo de iteración

Esta sección analiza el proceso subyacente de la iteración.

#### Iteración en todas partes

Muchos objetos diferentes admiten la iteración.

``` python
a = 'hello'
for c in a: # Recorrer caracteres en a
    ...

b = { 'name': 'Dave', 'password':'foo'}
for k in b: # Recorrer claves en diccionario
    ...

c = [1,2,3,4]
for i in c: # Recorrer elementos en una lista/tupla
    ...

f = open('foo.txt')
for x in f: # Recorrer líneas en un archivo
    ...
```

#### Iteración: Protocolo

Considere la declaración `for`.

```` python
for x in obj:
    # declaraciones
    ```

¿Qué sucede en segundo plano?

```python
_iter = obj.__iter__() # Obtener objeto iterador
while True:
    try:
        x = _iter.__next__() # Obtener siguiente elemento
        # declaraciones ...
    except StopIteration: # No más elementos
        break
````

Todos los objetos que funcionan con el `bucle for` implementan este protocolo de iteración de bajo nivel.

Ejemplo: Iteración manual sobre una lista.

``` python
>>> x = [1,2,3]
>>> it = x.__iter__()
>>> it
<listiterator object at 0x590b0>
>>> it.__next__()
1
>>> it.__next__()
2
>>> it.__next__()
3
>>> it.__next__()
Traceback (most recent call last):
File "<stdin>", line 1, in ? StopIteration
>>>
```

#### Soporte de iteración

Conocer la iteración es útil si desea agregarla a sus propios objetos. Por ejemplo, crear un contenedor personalizado.

``` python
class Portfolio:
    def __init__(self):
        self.holdings = []

    def __iter__(self):
        return self.holdings.__iter__()
    ...

port = Portfolio()
for s in port:
    ...
```

#### Ejercicios

##### Ejercicio 6.1: Iteración ilustrada

Cree la siguiente lista:

``` python
a = [1,9,4,25,16]
```

Itere manualmente sobre esta lista. Llame a `__iter__()` para obtener un iterador y llame al método `__next__()` para obtener elementos sucesivos.

``` python
>>> i = a.__iter__()
>>> i
<listiterator object at 0x64c10>
>>> i.__next__()
1
>>> i.__next__()
9
>>> i.__next__()
4
>>> i.__next__()
25
>>> i.__next__()
16
>>> i.__next__()
Traceback (most recent call last):
Archivo "<stdin>", línea 1, en <module>
StopIteration
>>>
```

La función incorporada `next()` es un atajo para llamar al método `__next__()` de un iterador. Intente usarlo en un archivo:

``` python
>>> f = open('Data/portfolio.csv')
>>> f.__iter__() # Nota: Esto devuelve el archivo en sí
<_io.TextIOWrapper name='Data/portfolio.csv' mode='r' encoding='UTF-8'>
>>> next(f)
'name,shares,price\n'
>>> next(f)
'"AA",100,32.20\n'
>>> next(f)
'"IBM",50,91.10\n'
>>>
```

Siga llamando a `next(f)` hasta que llegue al final del archivo. Observe lo que sucede.

##### Ejercicio 6.2: Compatibilidad con iteraciones

En ocasiones, es posible que desee hacer que uno de sus propios objetos admita la iteración, especialmente si su objeto envuelve una lista existente u otro iterable. En un nuevo archivo `portfolio.py`, defina la siguiente clase:

``` python
# portfolio.py

class Portfolio:

    def __init__(self, holdings):
        self._holdings = holdings

    @property
    def total_cost(self):
        return sum([s.cost for s in self._holdings])

    def tabulate_shares(self):
        from collections import Counter
        total_shares = Counter()
        for s in self._holdings:
            total_shares[s.name] += s.shares
        return total_shares
```

Esta clase está pensada para ser una capa alrededor de una lista, pero con algunos métodos adicionales como la propiedad `total_cost`. Modifique la función `read_portfolio()` en `report.py` para que cree una instancia `Portfolio` como esta:

``` python
# report.py
...

import fileparse
from stock import Stock
from portfolio import Portfolio

def read_portfolio(filename):
    '''
    Lee un archivo de cartera de acciones en una lista de diccionarios con claves
    name, shares, and price.
    '''
    with open(filename) as file:
        portdicts = fileparse.parse_csv(file,
                                        select=['name','shares','price'],
                                        types=[str,int,float])

    portfolio = [ Stock(d['name'], d['shares'], d['price']) for d in portdicts ]
    return Portfolio(portfolio)
...
```

Intente ejecutar el programa `report.py`. Descubrirás que falla espectacularmente debido al hecho de que las instancias de "Portfolio" no son iterables.

``` python
>>> import report
>>> report.portfolio_report('Data/portfolio.csv', 'Data/prices.csv')
... falla...
```

Solucione esto modificando la clase `Portfolio` para que admita la iteración:

``` python
class Portfolio:

    def __init__(self, holdings):
        self._holdings = holdings

    def __iter__(self):
        return self._holdings.__iter__()

    @property
    def total_cost(self):
        return sum([s.shares*s.price for s in self._holdings])

    def tabulate_shares(self):
        from collections import Counter
        total_shares = Counter()
        for s in self._holdings:
            total_shares[s.name] += s.shares
        return total_shares
```

Después de realizar este cambio, su programa `report.py` debería funcionar nuevamente. Mientras lo hace, arregle su programa `pcost.py` para que use el nuevo objeto `Portfolio`. De esta manera:

``` python
# pcost.py

import report

def portfolio_cost(filename):
  '''
  Calcula el costo total (shares*price) de un archivo de cartera
  '''
  portfolio = report.read_portfolio(filename)
  return portfolio.total_cost
  ...
```

Pruébelo para asegurarse de que funciona:

``` python
>>> import pcost
>>> pcost.portfolio_cost('Data/portfolio.csv')
44671.15
>>>
```

##### Ejercicio 6.3: Cómo crear un contenedor más apropiado

Si crea una clase contenedora, a menudo querrá hacer más que solo iterar. Modifique la clase `Portfolio` para que tenga otros métodos especiales como este:

``` python
class Portfolio:
    def __init__(self, holdings):
        self._holdings = holdings

    def __iter__(self):
        return self._holdings.__iter__()

    def __len__(self):
        return len(self._holdings)

    def __getitem__(self, index):
        return self._holdings[index]

    def __contains__(self, name):
        return any([s.name == name for s in self._holdings])

    @property
    def total_cost(self):
        return sum([s.shares*s.price for s in self._holdings])

    def tabulate_shares(self):
        from collections import Counter
        total_shares = Counter()
        for s in self._holdings:
            total_shares[s.name] += s.shares
        return total_shares
```

Ahora, prueba algunos experimentos usando esta nueva clase:

``` python
>>> import report
>>> portfolio = report.read_portfolio('Data/portfolio.csv')
>>> len(portfolio)
7
>>> portfolio[0]
Stock('AA', 100, 32.2)
>>> portfolio[1]
Stock('IBM', 50, 91.1)
>>> portfolio[0:3]
[Stock('AA', 100, 32.2), Stock('IBM', 50, 91.1), Stock('CAT', 150, 83.44)]
>>> 'IBM' in portfolio
True
>>> 'AAPL' in portfolio
False
>>>
```

Una observación importante sobre esto: en general, el código se considera "Pythonic" si habla el vocabulario común de cómo funcionan normalmente otras partes de Python. Para los objetos contenedores, la compatibilidad con la iteración, la indexación, la contención y otros tipos de operadores es una parte importante de esto.

[Contenido](../Contents.Rmd) \| [Anterior (5.2 Técnicas de encapsulación)](../05_Object_model/02_Classes_encapsulation.Rmd) \| [Próximo (6.2 Personalización de la iteración con generadores)](02_Customizing_iteration.Rmd)
