---
title: "04_More_generators"
output: html_document
---

[Contenido](../Contents.Rmd) \| [Anterior (6.3 Problemas y flujos de trabajo de productores y consumidores)](03_Producers_consumers.Rmd) \| [Próximo (7. Algunos temas avanzados)](../07_Advanced_Topics/00_Overview.Rmd)

### 6.4 Más generadores

Esta sección presenta algunos temas adicionales relacionados con los generadores, incluidas las expresiones de generador y el módulo `itertools`.

#### Expresiones generadoras

Una versión de generador de una lista por comprensión.

``` python
>>> a = [1,2,3,4]
>>> b = (2*x for x in a)
>>> b
<generator object at 0x58760>
>>> for i in b:
... print(i, end=' ')
...
2 4 6 8
>>>
```

Diferencias con las listas por comprensión.

-   No construye una lista.
-   El único propósito útil es la iteración.
-   Una vez consumido, no se puede reutilizar.

Sintaxis general.

``` python
(<expresión> for i in s if <condicional>)
```

También puede servir como argumento de función.

``` python
sum(x*x for x in a)
```

Se puede aplicar a cualquier iterable.

``` python
>>> a = [1,2,3,4]
>>> b = (x*x for x in a)
>>> c = (-x for x in b)
>>> for i in c:
... print(i, end=' ')
...
-1 -4 -9 -16
>>>
```

El uso principal de las expresiones de generador es en código que realiza algún cálculo en una secuencia, pero solo usa el resultado una vez. Por ejemplo, eliminar todos los comentarios de un archivo.

``` python
f = open('somefile.txt')
lines = (line for line in f if not line.startswith('#'))
for line in lines:
    ...
f.close()
```

Con los generadores, el código se ejecuta más rápido y usa menos memoria. Es como un filtro aplicado a una secuencia.

#### Por qué generadores

-   Muchos problemas se expresan mucho más claramente en términos de iteración.
-   Recorrer una colección de elementos y realizar algún tipo de operación (buscar, reemplazar, modificar, etc.).
-   Las canalizaciones de procesamiento se pueden aplicar a una amplia gama de problemas de procesamiento de datos.
-   Mejor eficiencia de la memoria.
-   Solo se producen valores cuando es necesario.
-   Contraste con la construcción de listas gigantes.
-   Puede operar en datos en tiempo real.
-   Los generadores fomentan la reutilización de código.
-   Separa la *iteración* del código que utiliza la iteración.
-   Puede crear una caja de herramientas de funciones de iteración interesantes y *mezclar y combinar*.

#### Módulo `itertools`

`itertools` es un módulo de biblioteca con varias funciones diseñadas para ayudar con los iteradores/generadores.

``` python
itertools.chain(s1,s2)
itertools.count(n)
itertools.cycle(s)
itertools.dropwhile(predicate, s)
itertools.groupby(s)
itertools.ifilter(predicate, s)
itertools.imap(function, s1, ... sN)
itertools.repeat(s, n)
itertools.tee(s, ncopies)
itertools.izip(s1, ... , sN)
```

Todas las funciones procesan datos de forma iterativa. Implementan varios tipos de patrones de interación.

Más información en el tutorial [Generator Tricks for Systems Programmers](http://www.dabeaz.com/generators/) de PyCon '08.

#### Ejercicios

En los ejercicios anteriores, escribió un código que seguía las líneas que se escribían en un archivo de registro y las analizó en una secuencia de filas. Este ejercicio continúa basándose en eso. Asegúrese de que `Data/stocksim.py` todavía se esté ejecutando.

##### Ejercicio 6.13: Expresiones generadoras

Las expresiones generadoras son una versión generadora de una comprensión de lista. Por ejemplo:

``` python
>>> nums = [1, 2, 3, 4, 5]
>>> squares = (x*x for x in nums)
>>> squares
<generator object <genexpr> at 0x109207e60>
>>> for n in squares:
...     print(n)
...
1
4
9
16
25
```

A diferencia de una lista por comprensión, una expresión generadora solo se puede usar una vez. Por lo tanto, si intentas otro bucle for, no obtienes nada:

``` python
>>> for n in squares:
...     print(n)
...
>>>
```

##### Ejercicio 6.14: Expresiones generadoras en argumentos de función

A veces, las expresiones generadoras se colocan en los argumentos de función. Parece un poco extraño al principio, pero prueba este experimento:

``` python
>>> nums = [1,2,3,4,5]
>>> sum([x*x for x in nums]) # Una comprensión de lista
55
>>> sum(x*x for x in nums) # Una expresión generadora
55
>>>
```

En el ejemplo anterior, la segunda versión que usa generadores utilizaría significativamente menos memoria si se manipulara una lista grande.

En tu archivo `portfolio.py`, realizaste algunos cálculos que involucraban comprensiones de lista. Intente reemplazarlas con expresiones generadoras.

##### Ejercicio 6.15: Simplificación de código

Las expresiones generadoras suelen ser un reemplazo útil para funciones generadoras pequeñas. Por ejemplo, en lugar de escribir una función como esta:

``` python
def filter_symbols(rows, names):
    for row in rows:
        if row['name'] in names:
            yield row
```

Podría escribir algo como esto:

``` python
rows = (row for row in rows if row['name'] in names)
```

Modifique el programa `ticker.py` para usar expresiones generadoras según corresponda.

[Contenido](../Contents.Rmd) \| [Anterior (6.3 Problemas y flujos de trabajo de productores y consumidores)](03_Producers_consumers.Rmd) \| [Próximo (7. Algunos temas avanzados)](../07_Advanced_Topics/00_Overview.Rmd)
