---
title: "04_Sequences"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

[Contenido](../Contents.Rmd) \| [Anterior (2.3 Salida con
formato)](03_Formatting.Rmd) \| [Próximo (2.5 Módulo
Collections)](05_Collections.Rmd)

### 2.4 Secuencias

#### Tipos de datos de secuencia

Python tiene tres tipos de datos de *secuencia*.

-   Cadena: `'Hola'`. Una cadena es una secuencia de caracteres.
-   Lista: `[1, 4, 5]`.
-   Tupla: `('GOOG', 100, 490.1)`.

Todas las secuencias están ordenadas, indexadas por números enteros y
tienen una longitud.

``` python
a = 'Hello'               # String
b = [1, 4, 5]             # Lista
c = ('GOOG', 100, 490.1)  # Tupla

# Orden Indexado
a[0]                      # 'H'
b[-1]                     # 5
c[1]                      # 100

# Longitud de la secuencia
len(a)                    # 5
len(b)                    # 3
len(c)                    # 3
```

Las secuencias se pueden replicar: `s * n`.

``` python
>>> a = 'Hello'
>>> a * 3
'HelloHelloHello'
>>> b = [1, 2, 3]
>>> b * 2
[1, 2, 3, 1, 2, 3]
>>>
```

Las secuencias del mismo tipo se pueden concatenar: `s + t`.

``` python
>>> a = (1, 2, 3)
>>> b = (4, 5)
>>> a + b
(1, 2, 3, 4, 5)
>>>
>>> c = [1, 5]
>>> a + c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can only concatenate tuple (not "list") to tuple
```

#### Rebanar

Rebanar significa tomar una subsecuencia de una secuencia. La sintaxis
es `s[inicio:fin]`. Donde `inicio` y `fin` son los índices de la
subsecuencia que desea.

``` python
a = [0,1,2,3,4,5,6,7,8]

a[2:5]    # [2,3,4]
a[-5:]    # [4,5,6,7,8]
a[:3]     # [0,1,2]
```

-   Los índices `inicio` y `fin` deben ser números enteros.
-   Las porciones *no* incluyen el valor final. Es como un intervalo
    medio abierto de matemáticas.
-   Si se omiten los índices, el valor predeterminado es el principio o
    el final de la lista.

#### Reasignación de sectores

En las listas, las porciones se pueden reasignar y eliminar.

``` python
# Reasignación
a = [0,1,2,3,4,5,6,7,8]
a[2:4] = [10,11,12]       # [0,1,10,11,12,4,5,6,7,8]
```

*Nota: La porción reasignada no necesita tener la misma longitud.*

``` python
# Eliminación
a = [0,1,2,3,4,5,6,7,8]
del a[2:4]                # [0,1,4,5,6,7,8]
```

#### Reducciones de secuencia

Hay algunas funciones comunes para reducir una secuencia a un solo
valor.

``` python
>>> s = [1, 2, 3, 4]
>>> sum(s)
10
>>> min(s)
1
>>> max(s)
4
>>> t = ['Hola', 'Mundo']
>>> max(t)
'Mundo'
>>>
```

```         

#### Iteración sobre una secuencia

El bucle for itera sobre los elementos de una secuencia.

```python
>>> s = [1, 4, 9, 16]
>>> for i in s:
...     print(i)
...
1
4
9
16
>>>
```

En cada iteración del bucle, obtienes un nuevo elemento con el que
trabajar. Este nuevo valor se coloca en la variable de iteración. En
este ejemplo, la variable de iteración es `x`:

``` python
for x in s: # `x` es una variable de iteración
  ...declaraciones
```

En cada iteración, se sobrescribe el valor anterior de la variable de
iteración (si lo hay). Una vez finalizado el bucle, la variable conserva
el último valor.

#### Declaración `break`

Puede utilizar la declaración `break` para salir de un bucle antes de
tiempo.

``` python
for name in namelist:
    if name == 'Jake':
        break
    ...
    ...
declaraciones
```

Cuando se ejecuta la declaración `break`, sale del bucle y pasa a las
siguientes `declaraciones`. La declaración `break` sólo se aplica al
bucle más interno. Si este bucle está dentro de otro bucle, no romperá
el bucle externo.

#### Declaración `continue`

Para omitir un elemento y pasar al siguiente, utilice la instrucción
`continue`.

``` python
for line in lines:
    if line == '\n':    # Omite líneas en blanco
        continue
    # Más declaraciones
    ...
```

Esto es útil cuando el elemento actual no es de interés o no necesita
ser revisado, ignoradolo en el procesamiento.

#### Recorriendo números enteros

Si necesita contar, utilice `range()`.

``` python
for i in range(100):
    # i = 0,1,...,99
```

La sintaxis es `range([inicio,] fin [,paso])`

``` python
for i in range(100):
    # i = 0,1,...,99
for j in range(10,20):
    # j = 10,11,..., 19
for k in range(10,50,2):
    # k = 10,12,...,48
    # Observe que se cuenta en pasos de 2, no de 1.
```

\*El valor final nunca se incluye. Refleja el comportamiento de las
rebanadas.

-   `start` es opcional. Valor predeterminado `0`.
-   `step` es opcional. Valor predeterminado `1`.
-   `range()` calcula valores según sea necesario. En realidad no
    almacena un rango amplio de números.

#### Función enumerate()

La función `enumerate` agrega un valor de contador adicional a la
iteración.

``` python
names = ['Elwood', 'Jake', 'Curtis']
for i, name in enumerate(names):
    # Bucle con i = 0, name = 'Elwood'
    # i = 1, name = 'Jake'
    # i = 2, name = 'Curtis'
```

La forma general es `enumerate(secuencia [, inicio = 0])`. `start` es
opcional. Un buen ejemplo del uso de `enumerate()` es el seguimiento de
los números de línea mientras se lee un archivo:

``` python
with open(filename) as f:
    for lineno, line in enumerate(f, start=1):
        ...
```

Al final, `enumerate` es simplemente un buen atajo para:

``` python
i = 0
for x in s:
    statements
    i += 1
```

El uso de `enumerate` implica escribir menos y se ejecuta un poco más
rápido.

#### `for`y tuplas

Puedes iterar con múltiples variables de iteración.

``` python
points = [
  (1, 4),(10, 40),(23, 14),(5, 6),(7, 8)
]
for x, y in points:
    # Bucle con x = 1, y = 4
    #            x = 10, y = 40
    #            x = 23, y = 14
    #            ...
```

Cuando se utilizan múltiples variables, cada tupla se *desempaqueta* en
un conjunto de variables de iteración. El número de variables debe
coincidir con el número de elementos en cada tupla.

#### Función `zip()`

La función `zip` toma múltiples secuencias y crea un iterador que las
combina.

``` python
columns = ['name', 'shares', 'price']
values = ['GOOG', 100, 490.1 ]
pairs = zip(columns, values)
# ('name','GOOG'), ('shares',100), ('price',490.1)
```

Para obtener el resultado debes iterar. Puedes usar múltiples variables
para desempaquetar las tuplas como se mostró anteriormente.

``` python
for column, value in pairs:
    ...
```

Un uso común de `zip` es crear pares clave/valor para construir
diccionarios.

``` python
d = dict(zip(columns, values))
```

#### Ejercicios

##### Ejercicio 2.13: Contar

Pruebe algunos ejemplos básicos de conteo:

``` python
>>> for n in range(10):            # Count 0 ... 9
        print(n, end=' ')

0 1 2 3 4 5 6 7 8 9
>>> for n in range(10,0,-1):       # Count 10 ... 1
        print(n, end=' ')

10 9 8 7 6 5 4 3 2 1
>>> for n in range(0,10,2):        # Count 0, 2, ... 8
        print(n, end=' ')

0 2 4 6 8
>>>
```

##### Ejercicio 2.14: Más operaciones de secuencia

Experimente interactivamente con algunas de las operaciones de reducción
de secuencia.

``` python
>>> data = [4, 9, 1, 25, 16, 100, 49]
>>> min(data)
1
>>> max(data)
100
>>> sum(data)
204
>>>
```

Intente recorrer los datos en un bucle.

``` python
>>> data = [4, 9, 1, 25, 16, 100, 49]
>>> min(data)
1
>>> max(data)
100
>>> sum(data)
204
>>>
```

...

> > > for n, x in enumerate(data): print(n, x)

0 4 1 9 2 1 ... \>\>\>

```         

A veces, los novatos utilizan la declaración `for`, `len()` y `range()`
en algún tipo de fragmento de código horrible que parece surgido de las
profundidades de un programa C oxidado.

```python
>>> for n in range(len(data)):
        print(data[n])

4
9
1
...
>>>
```

¡No hagas eso! No sólo leerlo hace sangrar los ojos a todos, sino que
además es ineficiente con la memoria y funciona mucho más lento.
Simplemente use un bucle `for` normal si desea iterar sobre los datos.
Utilice `enumerate()` si necesita el índice por algún motivo.

##### Ejercicio 2.15: Un ejemplo práctico de enumerate()

Recuerde que el archivo `Data/missing.csv` contiene datos de una cartera
de acciones, pero tiene algunas filas con datos faltantes. Usando
`enumerate()`, modifique su programa `pcost.py` para que imprima un
número de línea con el mensaje de advertencia cuando encuentre una
entrada incorrecta.

``` python
>>> cost = portfolio_cost('Data/missing.csv')
Row 4: Couldn't convert: ['MSFT', '', '51.23'] # Fila 4: No se puede convertir
 Row 7: Couldn't convert: ['IBM', '', '70.44'] # Fila 7: No se puede convertir
>>>
```

Para hacer esto, necesitarás cambiar algunas partes de tu código.

``` python
...
for rowno, row in enumerate(rows, start=1):
    try:
        ...
    except ValueError:
        print(f'Row {rowno}: Bad row: {row}')
```

##### Ejercicio 2.16: Uso de la función `zip()`

En el archivo `Data/portfolio.csv`, la primera línea contiene
encabezados de columna. En todo el código anterior, los hemos estado
descartando.

``` python
>>> f = open('Data/portfolio.csv')
>>> rows = csv.reader(f)
>>> headers = next(rows)
>>> headers
['name', 'shares', 'price']
>>>
```

Pero ¿qué pasaría si pudieses usar los encabezados para algo útil? Aquí
es donde entra en escena la función `zip()`. Primero intente esto para
emparejar los encabezados de archivo con una fila de datos:

``` python
>>> row = next(rows)
>>> row
['AA', '100', '32.20']
>>> list(zip(headers, row))
[ ('name', 'AA'), ('shares', '100'), ('price', '32.20') ]
>>>
```

Observe cómo `zip()` emparejó los encabezados de columna con los valores
de columna. Aquí usamos `list()` para convertir el resultado en una
lista para que puedas verlo. Normalmente, `zip()` crea un iterador que
debe ser consumido por un bucle for.

Este emparejamiento es un paso intermedio para construir un diccionario.
Ahora prueba esto:

``` python
>>> record = dict(zip(headers, row))
>>> record
{'price': '32.20', 'name': 'AA', 'shares': '100'}
>>>
```

Esta transformación es uno de los trucos más útiles que debemos conocer
al procesar muchos archivos de datos. Por ejemplo, supongamos que desea
hacer que el programa `pcost.py` funcione con varios archivos de
entrada, pero sin tener en cuenta el número de columna real donde
aparecen el nombre, las acciones y el precio.

Modifique la función `portfolio_cost()` en `pcost.py` para que se vea
así:

``` python
# pcost.py

def portfolio_cost(filename):
    ...
        for rowno, row in enumerate(rows, start=1):
            record = dict(zip(headers, row))
            try:
                nshares = int(record['shares'])
                price = float(record['price'])
                total_cost += nshares * price
            # Esto detecta errores en las conversiones int() y float() anteriores
            except ValueError:
                print(f'Row {rowno}: Bad row: {row}')
        ...
```

Ahora, prueba tu función en un archivo de datos completamente diferente
`Data/portfoliodate.csv` que se ve así:

``` csv
name,date,time,shares,price
"AA","6/11/2007","9:50am",100,32.20
"IBM","5/13/2007","4:20pm",50,91.10
"CAT","9/23/2006","1:30pm",150,83.44
"MSFT","5/17/2007","10:30am",200,51.23
"GE","2/1/2006","10:45am",95,40.37
"MSFT","10/31/2006","12:05pm",50,65.10
"IBM","7/9/2006","3:15pm",100,70.44
```

``` python
>>> portfolio_cost('Data/portfoliodate.csv')
44671.15
>>>
```

Si lo hiciste bien, descubrirás que tu programa aún funciona. aunque el
archivo de datos tiene un formato de columna completamente diferente al
anterior. ¡Eso es genial!

El cambio realizado aquí es sutil, pero significativo. En lugar de que
`portfolio_cost()` esté codificado para leer un único formato de archivo
fijo, la nueva versión lee cualquier archivo CSV y selecciona los
valores de interés. Siempre que el archivo tenga las columnas
requeridas, el código funcionará.

Modifique el programa `report.py` que escribió en la Sección 2.3 para
que utilice la misma técnica para seleccionar los encabezados de
columna.

Intente ejecutar el programa `report.py` en el archivo
`Data/portfoliodate.csv` y verá que produce la misma respuesta que
antes.

##### Ejercicio 2.17: Invertir un diccionario

Un diccionario asigna claves a valores. Por ejemplo, un diccionario de
precios de acciones.

``` python
>>> prices = {
        'GOOG' : 490.1,
        'AA' : 23.45,
        'IBM' : 91.1,
        'MSFT' : 34.23
    }
>>>
```

Si utiliza el método `items()`, puede obtener pares `(clave, valor)`:

``` python
>>> prices.items()
dict_items([('GOOG', 490.1), ('AA', 23.45), ('IBM', 91.1), ('MSFT', 34.23)])
>>>
```

Sin embargo, ¿qué sucede si desea obtener una lista de pares '(valor,
clave)'? *Sugerencia: use `zip()`*.

``` python
>>> pricelist = list(zip(prices.values(),prices.keys()))
>>> pricelist
[(490.1, 'GOOG'), (23.45, 'AA'), (91.1, 'IBM'), (34.23, 'MSFT')]
>>>
```

¿Por qué harías esto? En primer lugar, permite realizar ciertos tipos de
procesamiento de datos en los datos del diccionario.

``` python
>>> min(pricelist)
(23.45, 'AA')
>>> max(pricelist)
(490.1, 'GOOG')
>>> sorted(pricelist)
[(23.45, 'AA'), (34.23, 'MSFT'), (91.1, 'IBM'), (490.1, 'GOOG')]
>>>
```

Esto también ilustra una característica importante de las tuplas. Cuando
se utilizan en comparaciones, las tuplas se comparan elemento por
elemento comenzando con el primer elemento. Similar a cómo se comparan
cadenas carácter por carácter.

`zip()` se usa a menudo en situaciones como ésta, donde es necesario
emparejar datos de diferentes lugares. Por ejemplo, emparejar los
nombres de las columnas con los valores de las columnas para crear un
diccionario de valores con nombre.

Tenga en cuenta que `zip()` no está limitado a pares. Por ejemplo,
puedes usarlo con cualquier número de listas de entrada:

``` python
>>> a = [1, 2, 3, 4]
>>> b = ['w', 'x', 'y', 'z']
>>> c = [0.2, 0.4, 0.6, 0.8]
>>> list(zip(a, b, c))
[(1, 'w', 0.2), (2, 'x', 0.4), (3, 'y', 0.6), (4, 'z', 0.8))]
>>>
```

Además, tenga en cuenta que `zip()` se detiene una vez que se agota la
secuencia de entrada más corta.

``` python
>>> a = [1, 2, 3, 4, 5, 6]
>>> b = ['x', 'y', 'z']
>>> list(zip(a,b))
[(1, 'x'), (2, 'y'), (3, 'z')]
>>>
```

[Contenido](../Contents.Rmd) \| [Anterior (2.3 Salida con
formato)](03_Formatting.Rmd) \| [Próximo (2.5 Módulo
Collections)](05_Collections.Rmd)
