---
title: "05_Collections"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

[Contenido](../Contents.Rmd) \| [Anterior (2.4
Secuencias)](04_Sequences.Rmd) \| [Siguiente (2.6 Listas por
comprensión)](06_List_comprehension.Rmd)

### 2.5 Módulo collections

El módulo `collections` proporciona una serie de objetos útiles para el
manejo de datos. En esta parte se presentan brevemente algunas de estas
características.

#### Ejemplo: Contar cosas

Digamos que desea tabular el total de acciones de cada acción.

``` python
portfolio = [
    ('GOOG', 100, 490.1),
    ('IBM', 50, 91.1),
    ('CAT', 150, 83.44),
    ('IBM', 100, 45.23),
    ('GOOG', 75, 572.45),
    ('AA', 50, 23.15)
]
```

Hay dos entradas `'IBM'` y dos entradas `'GOOG'` en esta lista. Las
acciones deben combinarse de alguna manera.

#### Contadores

Solución: Utilice un `Counter`.

``` python
from collections import Counter
total_shares = Counter()
for name, shares, price in portfolio:
    total_shares[name] += shares

total_shares['IBM']     # 150
```

#### Ejemplo: Asignaciones de uno a muchos

Problema: desea asignar una clave a múltiples valores.

``` python
portfolio = [
    ('GOOG', 100, 490.1),
    ('IBM', 50, 91.1),
    ('CAT', 150, 83.44),
    ('IBM', 100, 45.23),
    ('GOOG', 75, 572.45),
    ('AA', 50, 23.15)
]
```

Al igual que en el ejemplo anterior, la clave `'IBM'` debería tener dos
tuplas diferentes.

Solución: utilice un `defaultdict`.

``` python
from collections import defaultdict
holdings = defaultdict(list)
for name, shares, price in portfolio:
    holdings[name].append((shares, price))
holdings['IBM'] # [ (50, 91.1), (100, 45.23) ]
```

`defaultdict` garantiza que cada vez que accedas a una clave obtendrás
un valor predeterminado.

#### Ejemplo: Mantener un historial

Problema: Queremos un historial de las últimas N cosas. Solución:
utilice `deque`.

``` python
from collections import deque

history = deque(maxlen=N)
with open(filename) as f:
    for line in f:
        history.append(line)
        ...
```

#### Ejercicios

El módulo `collections` podría ser uno de los módulos de biblioteca más
útiles para tratar problemas de manejo de datos de propósitos
especiales, tales como tabulación e indexación.

En este ejercicio, veremos algunos ejemplos sencillos. Comience
ejecutando su programa `report.py` para que tenga la cartera de acciones
cargada en modo interactivo.

``` bash
bash % python3 -i report.py
```

##### Ejercicio 2.18: Tabulación con contadores

Supongamos que desea tabular la tenencia total de cada acción. Esto es
fácil usando objetos 'Counter'. Pruébalo:

``` python
>>> portfolio = read_portfolio('Data/portfolio.csv')
>>> from collections import Counter
>>> holdings = Counter()
>>> for s in portfolio:
        holdings[s['name']] += s['shares']

>>> holdings
Counter({'MSFT': 250, 'IBM': 150, 'CAT': 150, 'AA': 100, 'GE': 95})
>>>
```

Observe atentamente cómo las entradas múltiples para `'MSFT'` e `'IBM'`
en `portafolio` se combinan en una sola entrada aquí.

Puedes utilizar un contador como si fuera un diccionario para recuperar
valores individuales:

``` python
>>> holdings['IBM']
150
>>> holdings['MSFT']
250
>>>
```

Si desea clasificar los valores, haga lo siguiente:

``` python
>>> # Get three most held stocks
>>> holdings.most_common(3)
[('MSFT', 250), ('IBM', 150), ('CAT', 150)]
>>>
```

Tomemos otra cartera de acciones y creemos un nuevo contador:

``` python
>>> portfolio2 = read_portfolio('Data/portfolio2.csv')
>>> holdings2 = Counter()
>>> for s in portfolio2:
          holdings2[s['name']] += s['shares']

>>> holdings2
Counter({'HPQ': 250, 'GE': 125, 'AA': 50, 'MSFT': 25})
>>>
```

Por último, combinemos todos los activos realizando una sencilla
operación:

``` python
>>> holdings
Counter({'MSFT': 250, 'IBM': 150, 'CAT': 150, 'AA': 100, 'GE': 95})
>>> holdings2
Counter({'HPQ': 250, 'GE': 125, 'AA': 50, 'MSFT': 25})
>>> combined = holdings + holdings2
>>> combined
Counter({'MSFT': 275, 'HPQ': 250, 'GE': 220, 'AA': 150, 'IBM': 150, 'CAT': 150})
>>>
```

Esto es sólo una pequeña muestra de lo que los contadores ofrecen. Sin
embargo, si alguna vez necesitas tabular valores, deberías considerar
usar uno.

##### Comentario: módulo Collections

El módulo `collections` es uno de los módulos de biblioteca más útiles
de todo Python. De hecho, podríamos hacer un tutorial extenso sólo sobre
eso. Sin embargo, hacerlo ahora también sería una distracción. Por
ahora, pon `collections` en tu lista de lectura para antes de dormir,
para más tarde.

[Contenido](../Contents.Rmd) \| [Anterior (2.4
Secuencias)](04_Sequences.Rmd) \| [Siguiente (2.6 Listas por
comprensión)](06_List_comprehension.Rmd)
