## creative commons

# Attribution-ShareAlike 4.0 International

Creative Commons Corporation (“Creative Commons”) no es un bufete de abogados y no proporciona servicios legales ni asesoramiento legal. La distribución de licencias públicas de Creative Commons no crea una relación abogado-cliente ni de ningún otro tipo. Creative Commons pone a disposición sus licencias e información relacionada “tal cual”. Creative Commons no ofrece garantías con respecto a sus licencias, ningún material licenciado bajo sus términos y condiciones, ni ninguna información relacionada. Creative Commons renuncia a toda responsabilidad por daños resultantes de su uso en la mayor medida posible.

## Uso de licencias públicas de Creative Commons

Las licencias públicas de Creative Commons proporcionan un conjunto estándar de términos y condiciones que los creadores y otros titulares de derechos pueden utilizar para compartir obras originales de autoría y otro material sujeto a derechos de autor y otros derechos especificados en la licencia pública a continuación. Las siguientes consideraciones son solo para fines informativos, no son exhaustivas y no forman parte de nuestras licencias.

-   **Consideraciones para los licenciantes:** Nuestras licencias públicas están destinadas a ser utilizadas por aquellos autorizados a dar al público permiso para usar material en formas que de otro modo estarían restringidas por los derechos de autor y otros derechos determinados. Nuestras licencias son irrevocables. Los licenciantes deben leer y comprender los términos y condiciones de la licencia que elijan antes de aplicarla. Los licenciantes también deben asegurar todos los derechos necesarios antes de aplicar nuestras licencias para que el público pueda reutilizar el material como se espera. Los licenciantes deben marcar claramente cualquier material que no esté sujeto a la licencia. Esto incluye otro material con licencia CC o material utilizado bajo una excepción o limitación a los derechos de autor. [Más consideraciones para los licenciantes](http://wiki.creativecommons.org/Considerations_for_licensors_and_licensees#Considerations_for_licensors).

-   **Consideraciones para el público:** Al utilizar una de nuestras licencias públicas, un licenciante otorga al público permiso para usar el material con licencia bajo términos y condiciones específicos. Si el permiso del licenciante no es necesario por algún motivo (por ejemplo, debido a alguna excepción o limitación aplicable a los derechos de autor), entonces ese uso no está regulado por la licencia. Nuestras licencias otorgan únicamente permisos en virtud de los derechos de autor y otros derechos que el licenciante tiene autoridad para otorgar. El uso del material licenciado puede estar restringido por otros motivos, incluso porque otros tengan derechos de autor u otros derechos sobre el material. El licenciante puede hacer solicitudes especiales, como pedir que se marquen o describan todos los cambios. Aunque nuestras licencias no lo exigen, se recomienda que respete esas solicitudes cuando sea razonable. [Más consideraciones para el público](http://wiki.creativecommons.org/Considerations_for_licensors_and_licensees#Considerations_for_licensees).

## Licencia pública internacional Creative Commons Attribution-ShareAlike 4.0

Al ejercer los derechos licenciados (definidos a continuación), acepta y se compromete a cumplir los términos y condiciones de esta licencia pública internacional Creative Commons Attribution-ShareAlike 4.0 ("Licencia pública"). En la medida en que esta Licencia Pública pueda interpretarse como un contrato, se le otorgan los Derechos Licenciados a cambio de su aceptación de estos términos y condiciones, y el Licenciante le otorga dichos derechos a cambio de los beneficios que recibe al poner a disposición el Material Licenciado de conformidad con estos términos y condiciones.

### Sección 1 – Definiciones.

a.  **Material Adaptado** significa material sujeto a Derechos de Autor y Derechos Similares que se deriva de o se basa en el Material Licenciado y en el que el Material Licenciado se traduce, altera, arregla, transforma o modifica de otra manera de una manera que requiere permiso de conformidad con los Derechos de Autor y Derechos Similares que posee el Licenciante. Para los fines de esta Licencia Pública, cuando el Material Licenciado es una obra musical, una interpretación o una grabación de sonido, el Material Adaptado siempre se produce cuando el Material Licenciado está sincronizado en relación temporal con una imagen en movimiento.

b.  **Licencia del Adaptador** significa la licencia que Usted aplica a sus Derechos de Autor y Derechos Similares en sus contribuciones al Material Adaptado de conformidad con los términos y condiciones de esta Licencia Pública.

c.  **Licencia compatible con BY-SA** significa una licencia incluida en [creativecommons.org/compatiblelicenses](http://creativecommons.org/compatiblelicenses), aprobada por Creative Commons como esencialmente equivalente a esta Licencia pública.

d.  **Copyright y derechos similares** significa copyright y/o derechos similares estrechamente relacionados con el copyright, incluidos, sin limitación, derechos de ejecución, transmisión, grabación de sonido y derechos de base de datos sui generis, sin importar cómo se etiqueten o categoricen los derechos. Para los fines de esta Licencia pública, los derechos especificados en la Sección 2(b)(1)-(2) no son derechos de autor y derechos similares.

e.  **Medidas tecnológicas efectivas** significa aquellas medidas que, en ausencia de una autoridad adecuada, no pueden eludirse en virtud de leyes que cumplan con las obligaciones establecidas en el Artículo 11 del Tratado de la OMPI sobre Derecho de Autor adoptado el 20 de diciembre de 1996 y/o acuerdos internacionales similares.

f.  **Excepciones y limitaciones** significa uso justo, trato justo y/o cualquier otra excepción o limitación a los derechos de autor y derechos similares que se aplique a Su uso del Material con licencia.

g.  **Elementos de la licencia** significa los atributos de la licencia enumerados en el nombre de una Licencia pública de Creative Commons. Los elementos de la licencia de esta Licencia pública son Atribución y Compartir por igual.

h.  **Material con licencia** significa la obra artística o literaria, base de datos u otro material al que el Licenciante aplicó esta Licencia pública.

i.  **Derechos Licenciados** significa los derechos que se le otorgan a Usted sujetos a los términos y condiciones de esta Licencia Pública, que se limitan a todos los Derechos de Autor y Derechos Similares que se aplican a Su uso del Material Licenciado y que el Licenciante tiene autoridad para licenciar.

j.  **Licenciante** significa la(s) persona(s) o entidad(es) que otorgan derechos bajo esta Licencia Pública.

k.  **Compartir** significa proporcionar material al público por cualquier medio o proceso que requiera permiso bajo los Derechos Licenciados, como reproducción, exhibición pública, presentación pública, distribución, difusión, comunicación o importación, y poner material a disposición del público, incluso de maneras en que los miembros del público puedan acceder al material desde un lugar y en un momento elegidos individualmente por ellos.

l.  **Derechos Sui Generis de Bases de Datos** significa derechos distintos de los derechos de autor resultantes de la Directiva 96/9/CE del Parlamento Europeo y del Consejo del 11 de marzo de 1996 sobre la protección jurídica de las bases de datos, en su forma enmendada y/o sucedida, así como otros derechos esencialmente equivalentes en cualquier parte del mundo.

m.  **Usted** significa la persona o entidad que ejerce los Derechos Licenciados bajo esta Licencia Pública. Su tiene un significado correspondiente.

### Sección 2 – Alcance.

a.  ***Concesión de la licencia.***

<!-- -->

1.  Sujeto a los términos y condiciones de esta Licencia Pública, el Licenciante le otorga por la presente una licencia mundial, libre de regalías, no sublicenciable, no exclusiva e irrevocable para ejercer los Derechos Licenciados en el Material Licenciado para:

A. reproducir y Compartir el Material Licenciado, en su totalidad o en parte; y

B. producir, reproducir y Compartir Material Adaptado.

2.  **Excepciones y Limitaciones.** Para evitar dudas, cuando las Excepciones y Limitaciones se aplican a Su uso, esta Licencia Pública no se aplica y Usted no necesita cumplir con sus términos y condiciones.

3.  **Plazo.** El plazo de esta Licencia Pública se especifica en la Sección 6(a).

4.  **Medios y formatos; modificaciones técnicas permitidas.** El Licenciante lo autoriza a ejercer los Derechos Licenciados en todos los medios y formatos ya sean conocidos o creados en el futuro, y a realizar las modificaciones técnicas necesarias para ello. El Licenciante renuncia y/o acepta no hacer valer ningún derecho o autoridad para prohibirle realizar las modificaciones técnicas necesarias para ejercer los Derechos Licenciados, incluidas las modificaciones técnicas necesarias para eludir las Medidas Tecnológicas Efectivas. Para los fines de esta Licencia Pública, la simple realización de modificaciones autorizadas por esta Sección 2(a)(4) nunca produce Material Adaptado.

5.  **Destinatarios posteriores.**

A. **Oferta del Licenciante: Material Licenciado.** Todo destinatario del Material Licenciado recibe automáticamente una oferta del Licenciante para ejercer los Derechos Licenciados según los términos y condiciones de esta Licencia Pública.

B. \_\_Oferta adicional del Licenciante: Material Adaptado. Cada receptor de Material Adaptado de Usted recibe automáticamente una oferta del Licenciante para ejercer los Derechos Licenciados en el Material Adaptado bajo las condiciones de la Licencia del Adaptador que Usted aplique.

C. **Sin restricciones posteriores.** Usted no puede ofrecer ni imponer términos o condiciones adicionales o diferentes, ni aplicar Medidas Tecnológicas Efectivas al Material Licenciado si al hacerlo restringe el ejercicio de los Derechos Licenciados por cualquier receptor del Material Licenciado.

6.  **Sin respaldo.** Nada en esta Licencia Pública constituye ni puede interpretarse como un permiso para afirmar o implicar que Usted está, o que Su uso del Material Licenciado está, relacionado con, o patrocinado, respaldado o concedido estatus oficial por, el Licenciante u otros designados para recibir atribución según lo dispuesto en la Sección 3(a)(1)(A)(i).

<!-- -->

b.  ***Otros derechos.***

<!-- -->

1.  Los derechos morales, como el derecho a la integridad, no están licenciados bajo esta Licencia Pública, ni tampoco lo están los derechos de publicidad, privacidad y/u otros derechos de personalidad similares; Sin embargo, en la medida de lo posible, el Licenciante renuncia y/o acepta no hacer valer dichos derechos que posee en la medida limitada necesaria para permitirle ejercer los Derechos Licenciados, pero no de otra manera.

2.  Patente y cesión de derechos a cobrarle regalías por el ejercicio de los Derechos Licenciados, ya sea directamente o a través de una sociedad de recaudación en virtud de cualquier esquema de licencia obligatoria o estatutaria voluntaria o renunciable. En todos los demás casos, el Licenciante se reserva expresamente cualquier derecho a cobrar dichas regalías.

### Sección 3 – Condiciones de la Licencia.

Su ejercicio de los Derechos Licenciados está expresamente sujeto a las siguientes condiciones.

a.  ***Atribución.***

<!-- -->

1.  Si comparte el Material Licenciado (incluso en forma modificada), debe:

A. conservar lo siguiente si el Licenciante lo proporciona con el Material Licenciado:

i.  identificación del(los) creador(es) del Material Licenciado y cualquier otra persona designada para recibir atribución, de cualquier manera razonable solicitada por el Licenciante (incluso mediante seudónimo si se designa);

ii. un aviso de derechos de autor;

iii. un aviso que haga referencia a esta Licencia Pública;

iv. un aviso que haga referencia a la exención de garantías;

v.  un URI o hipervínculo al Material Licenciado en la medida en que sea razonablemente posible;

B. indicar si modificó el Material Licenciado y conservar una indicación de cualquier modificación anterior; y

C. indicar que el Material Licenciado está licenciado bajo esta Licencia Pública e incluir el texto de, o el URI o hipervínculo a, esta Licencia Pública.

2.  Puede cumplir con las condiciones de la Sección 3(a)(1) de cualquier manera razonable según el medio, los medios y el contexto en los que comparta el Material Licenciado. Por ejemplo, puede ser razonable cumplir con las condiciones proporcionando un URI o hipervínculo a un recurso que incluya la información requerida.

3.  Si el Licenciante lo solicita, debe eliminar cualquier información requerida por la Sección 3(a)(1)(A) en la medida en que sea razonablemente posible.

<!-- -->

b.  ***ShareAlike.***

Además de las condiciones de la Sección 3(a), si comparte material adaptado que produce, también se aplican las siguientes condiciones.

1.  La Licencia del Adaptador que usted aplica debe ser una licencia Creative Commons con los mismos Elementos de Licencia, esta versión o posterior, o una Licencia Compatible con BY-SA.

2.  Usted debe incluir el texto, el URI o el hipervínculo a la Licencia del Adaptador que usted aplica. Usted puede satisfacer esta condición de cualquier manera razonable en función del medio, los medios y el contexto en el que Usted Comparte el Material Adaptado.

3.  Usted no puede ofrecer ni imponer términos o condiciones adicionales o diferentes, ni aplicar Medidas Tecnológicas Efectivas al Material Adaptado que restrinjan el ejercicio de los derechos otorgados bajo la Licencia del Adaptador que usted aplica.

### Sección 4 – Derechos de Base de Datos Sui Generis.

Cuando los Derechos Licenciados incluyen Derechos de Base de Datos Sui Generis que se aplican a Su uso del Material Licenciado:

a.  para evitar dudas, la Sección 2(a)(1) le otorga el derecho a extraer, reutilizar, reproducir y Compartir todo o una parte sustancial de los contenidos de la base de datos;

b.  Si incluye la totalidad o una parte sustancial del contenido de la base de datos en una base de datos en la que tiene derechos sui generis sobre la base de datos, entonces la base de datos en la que tiene derechos sui generis sobre la base de datos (pero no su contenido individual) es material adaptado, incluso a los efectos de la Sección 3(b); y

c.  Debe cumplir con las condiciones de la Sección 3(a) si comparte la totalidad o una parte sustancial del contenido de la base de datos.

Para evitar dudas, esta Sección 4 complementa y no reemplaza sus obligaciones bajo esta Licencia Pública cuando los Derechos Licenciados incluyen otros Derechos de Autor y Derechos Similares.

### Sección 5 – Renuncia de garantías y limitación de responsabilidad.

a.  **A menos que el Licenciante acuerde lo contrario por separado, en la medida de lo posible, el Licenciante ofrece el Material Licenciado tal como está y tal como está disponible, y no realiza declaraciones ni garantías de ningún tipo con respecto al Material Licenciado, ya sean expresas, implícitas, legales u otras. Esto incluye, sin limitación, garantías de título, comerciabilidad, idoneidad para un fin determinado, no infracción, ausencia de defectos latentes o de otro tipo, precisión o presencia o ausencia de errores, sean o no conocidos o detectables. Cuando no se permitan descargos de responsabilidad de garantías en su totalidad o en parte, es posible que este descargo de responsabilidad no se aplique en su caso.**

b.  **En la medida de lo posible, en ningún caso el Licenciante será responsable ante Usted en virtud de ninguna teoría legal (incluida, sin limitación, la negligencia) o de otro modo por pérdidas, costos, gastos o daños directos, especiales, indirectos, incidentales, consecuentes, punitivos, ejemplares u otros que surjan de esta Licencia Pública o del uso del Material Licenciado, incluso si se le ha advertido al Licenciante de la posibilidad de dichas pérdidas, costos, gastos o daños. Cuando no se permita una limitación de responsabilidad en su totalidad o en parte, es posible que esta limitación no se aplique en su caso.**

c.  La exención de garantías y la limitación de responsabilidad que se proporcionan anteriormente se interpretarán de manera que, en la medida de lo posible, se respete la exención de responsabilidad y la renuncia a toda responsabilidad.

### Sección 6: - Plazo y terminación.

a.  Esta Licencia Pública se aplica durante el plazo de los derechos de autor y derechos similares aquí licenciados. Sin embargo, si no cumple con esta Licencia Pública, sus derechos bajo esta Licencia Pública terminarán automáticamente.

b.  Cuando su derecho a usar el Material Licenciado haya terminado según la Sección 6(a), se restablecerá:

<!-- -->

1.  automáticamente a partir de la fecha en que se corrija la infracción, siempre que se corrija dentro de los 30 días posteriores a que usted descubra la infracción; o

2.  tras el restablecimiento expreso por parte del Licenciante.

Para evitar dudas, esta Sección 6(b) no afecta ningún derecho que el Licenciante pueda tener para buscar remedios por sus infracciones de esta Licencia Pública.

c.  Para evitar dudas, el Licenciante también puede ofrecer el Material Licenciado bajo términos o condiciones separados o dejar de distribuir el Material Licenciado en cualquier momento; sin embargo, hacerlo no terminará esta Licencia Pública.

d.  Las Secciones 1, 5, 6, 7 y 8 sobreviven a la terminación de esta Licencia Pública.

### Sección 7 – Otros Términos y Condiciones.

a.  El Licenciante no estará obligado por ningún término o condición adicional o diferente comunicado por Usted a menos que se acuerde expresamente.

b.  Todos los arreglos, entendimientos o acuerdos con respecto al Material Licenciado que no se indiquen en este documento son separados e independientes de los términos y condiciones de esta Licencia Pública.

### Sección 8 – Interpretación.

a.  Para evitar dudas, esta Licencia Pública no reduce, limita, restringe ni impone condiciones sobre ningún uso del Material Licenciado que pudiera realizarse legalmente sin permiso bajo esta Licencia Pública, y no se interpretará que lo hace.

b.  En la medida de lo posible, si alguna disposición de esta Licencia Pública se considera inaplicable, se reformará automáticamente en la medida mínima necesaria para que sea aplicable. Si la disposición no se puede reformar, se separará de esta Licencia Pública sin afectar la aplicabilidad de los términos y condiciones restantes.

c.  No se eximirá ningún término o condición de esta Licencia Pública ni se consentirá ningún incumplimiento a menos que el Licenciante lo acepte expresamente.

d.  Nada de lo dispuesto en esta Licencia Pública constituye ni puede interpretarse como una limitación o renuncia a los privilegios e inmunidades que se aplican al Licenciante o a Usted, incluidos los de los procesos legales de cualquier jurisdicción o autoridad.

```         
Creative Commons no es parte de sus licencias públicas. No obstante, Creative Commons puede optar por aplicar una de sus licencias públicas al material que publica y, en esos casos, se considerará el "Licenciante". Excepto con el propósito limitado de indicar que el material se comparte bajo una licencia pública de Creative Commons o según lo permitan las políticas de Creative Commons publicadas en [creativecommons.org/policies](http://creativecommons.org/policies), Creative Commons no autoriza el uso de la marca registrada “Creative Commons” ni de ninguna otra marca registrada o logotipo de Creative Commons sin su consentimiento previo por escrito, incluyendo, sin limitación, en relación con cualquier modificación no autorizada de cualquiera de sus licencias públicas o cualquier otro acuerdo, entendimiento o convenio relativo al uso de material con licencia. Para evitar dudas, este párrafo no forma parte de las licencias públicas.

Puede ponerse en contacto con Creative Commons en creativecommons.org
```
