---
output:
  html_document: default
  pdf_document: default
editor_options: 
  markdown: 
    wrap: 72
---

# ¡Bienvenidos!

Esta es una versión en **Español** del curso [**Practical Python
Programming**](https://dabeaz-course.github.io/practical-python/)

A partir de ahora todo es obra de --David Beazley
(<https://dabeaz.com>), [\@dabeaz](https://mastodon.social/@dabeaz).

Cuando aprendí Python por primera vez hace casi 27 años, me sorprendió
de inmediato cómo podía aplicarlo de manera productiva a todo tipo de
proyectos laborales complicados. Una década después, me encontré
enseñándoles a otros la misma diversión. El resultado de esa enseñanza
es este curso: un curso de Python que se ha enseñado activamente a más
de 400 grupos en persona desde 2007. Traders, administradores de
sistemas, astrónomos, pensadores e incluso unos cientos de científicos
espaciales que usaron Python para ayudar a aterrizar un rover en Marte,
todos han tomado este curso. Ahora, me complace ponerlo a disposición
bajo una licencia Creative Commons, completamente libre de spam,
registros y otras tonterías. ¡Disfrútelo!

(P.D.: Este curso trata sobre Python. Si quieres un curso de Python que
trate sobre programación, podrías considerar [Programación avanzada con
Python](https://www.dabeaz.com/advprog.html))

## ¿Qué es esto?

El material que ves aquí es el núcleo de un curso de capacitación de
Python dirigido por un instructor que se utiliza para la capacitación
corporativa y el desarrollo profesional. Estuvo en desarrollo continuo
desde 2007 hasta 2019 y se probó en clases del mundo real. Por lo
general, se enseña en persona durante un período de tres o cuatro días,
lo que requiere aproximadamente entre 25 y 35 horas de trabajo intenso.
Esto incluye la realización de aproximadamente 130 ejercicios prácticos
de codificación.

## Público objetivo

Los estudiantes de este curso suelen ser científicos, ingenieros y
programadores profesionales que ya tienen experiencia en al menos otro
lenguaje de programación. No se requieren conocimientos previos de
Python, pero se supone que se tienen conocimientos de temas de
programación comunes. La mayoría de los participantes encuentran el
curso desafiante, incluso si ya han estado haciendo un poco de
programación en Python.

## Objetivos del curso

El objetivo de este curso es cubrir los aspectos fundamentales de la
programación en Python con énfasis en la escritura de scripts, la
manipulación básica de datos y la organización de programas. Al final de
este curso, los estudiantes deberían ser capaces de comenzar a escribir
programas útiles en Python por su cuenta o poder comprender y modificar
el código Python escrito por sus compañeros de trabajo.

## Requisitos

Para completar este curso, no necesita nada más que una instalación
básica de Python 3.6 o una versión más reciente y tiempo para trabajar
en ella.

## Qué no es este curso

Este no es un curso para principiantes absolutos sobre cómo programar
una computadora. Se supone que ya tienes experiencia en programación en
algún otro lenguaje de programación o en Python.

Este no es un curso sobre desarrollo web. Ese es un circo diferente. Sin
embargo, si te quedas para este circo, verás algunos actos interesantes,
pero nada que involucre animales.

Este no es un curso sobre el uso de herramientas que están escritas en
Python. Se trata de aprender el lenguaje Python central.

Este no es un curso para ingenieros de software sobre cómo escribir o
mantener una aplicación Python de un millón de líneas. No escribo
programas de ese tipo, ni tampoco lo hacen la mayoría de las empresas
que usan Python, y tú tampoco deberías hacerlo. ¡Elimina algo de una
vez!

## ¡Llévame al curso ya!

Ok, ok. ¡Apunta tu navegador [AQUÍ](Notes/Contents.md)!

## Discusión de la comunidad

¿Quieres debatir sobre el curso? Puedes unirte a la conversación en
[Gitter](https://gitter.im/dabeaz-course/practical-python). No puedo
prometer una respuesta individual, pero quizás otros puedan sumarse para
ayudar.

## Agradecimientos

Llorenç Muntaner fue fundamental en la conversión del contenido del
curso de Apple Keynote a la estructura en línea que ves aquí.

Varios instructores han presentado este curso en un momento u otro
durante los últimos 12 años. Esto incluye (en orden alfabético): Ned
Batchelder, Juan Pablo Claude, Mark Fenner, Michael Foord, Matt
Harrison, Raymond Hettinger, Daniel Klein, Travis Oliphant, James
Powell, Michael Selik, Hugo Shi, Ian Stokes-Rees, Yarko Tymciurak, Bryan
Van de ven, Peter Wang y Mark Wiebe.

También me gustaría agradecer a los miles de estudiantes que han
realizado este curso y han contribuido a su éxito con sus comentarios y
discusiones.

## Preguntas y respuestas

### P: ¿Hay videos del curso que pueda ver?

No. Este curso se trata de que usted escriba código Python, no de ver a
otra persona.

### P: ¿Cómo se licencia este curso?

Practical Python Programming tiene licencia Creative Commons Attribution
ShareAlike 4.0 International License.

### P: ¿Puedo usar este material para enseñar mi propio curso de Python?

Sí, siempre que se indique la atribución correspondiente.

### P: ¿Puedo hacer trabajos derivados?

Sí, siempre que dichos trabajos tengan los mismos términos de licencia y
proporcionen la atribución.

### P: ¿Puedo traducir esto a otro idioma?

Sí, eso sería genial. Envíeme un enlace cuando haya terminado.

### P: ¿Puedo transmitir en vivo el curso o hacer un video?

¡Sí, adelante! Probablemente aprenderás mucho de Python haciendo eso.

### P: ¿Por qué no se cubrió el tema X?

Hay una cantidad limitada de material que se puede cubrir en 3 o 4 días.
Si no se cubrió, probablemente fue porque se cubrió una vez y hizo que a
todos les explotara la cabeza o nunca hubo tiempo suficiente para
cubrirlo en primer lugar. Además, este es un curso, no un manual de
referencia de Python.

### P: ¿Por qué no se cubre el increíble `{command}` en el increíble `{tool}`?

El enfoque de este curso es aprender el lenguaje Python central, no
aprender los nombres de los comandos en las herramientas.

### P: ¿Este curso se mantiene o se actualiza?

Este curso representa un "producto terminado" que se enseñó y desarrolló
durante más de una década. No tengo planes de revisar significativamente
el material en este momento, pero ocasionalmente corregiré errores y
agregaré aclaraciones.

### P: ¿Aceptan solicitudes de incorporación de cambios?

Se agradecen los informes de errores y pueden enviarse a través del
[seguimiento de
problemas](https://github.com/dabeaz-course/practical-python/issues). No
se aceptan solicitudes de incorporación de cambios, excepto por
invitación. Primero, envíe un informe de problemas.
