---
title: "02_More_functions"
output: html_document
---

[Contenido](../Contents.Rmd) \| [Anterior (3.1 Funciones y escritura de scripts)](01_Script.Rmd) \| [Próximo (3.3 Comprobación de errores)](03_Error_checking.Rmd)

### 3.2 Más detalles sobre las funciones

Aunque las funciones se introdujeron anteriormente, se proporcionaron muy pocos detalles sobre cómo funcionan realmente en un nivel más profundo. Esta sección tiene como objetivo llenar algunos vacíos y analizar cuestiones como las convenciones de llamadas, las reglas de alcance y más.

#### Llamada a una función

Considere esta función:

``` python
def read_prices(filename, debug):
    ...
```

Puede llamar a la función con argumentos posicionales:

```         
prices = read_prices('prices.csv', True)
```

O puede llamar a la función con argumentos de palabras clave:

``` python
prices = read_prices(filename='prices.csv', debug=True)
```

#### Argumentos predeterminados

A veces desea que un argumento sea opcional. Si es así, asigne un valor predeterminado en la definición de la función.

``` python
def read_prices(filename, debug=False):
    ...
```

Si se asigna un valor predeterminado, el argumento es opcional en las llamadas a la función.

``` python
d = read_prices('prices.csv')
e = read_prices('prices.dat', True)
```

*Nota: Los argumentos con valores predeterminados deben aparecer al final de la lista de argumentos (todos los argumentos no opcionales van primero).*

#### Prefiera argumentos de palabras clave para argumentos opcionales

Compare y contraste estos dos estilos de llamada diferentes:

``` python
parse_data(data, False, True) # ?????

parse_data(data, ignore_errors=True)
parse_data(data, debug=True)
parse_data(data, debug=True, ignore_errors=True)
```

En la mayoría de los casos, los argumentos de palabras clave mejoran la claridad del código, especialmente para los argumentos que sirven como indicadores o que están relacionados con características opcionales.

#### Mejores prácticas de diseño

Siempre de nombres breves, pero significativos, a los argumentos de las funciones.

Alguien que use una función puede querer usar el estilo de llamada de palabras clave.

``` python
d = read_prices('prices.csv', debug=True)
```

Las herramientas de desarrollo de Python mostrarán los nombres en las funciones de ayuda y la documentación.

#### Valores de retorno

La declaración `return` devuelve un valor

``` python
def square(x):
    return x * x
```

Si no se proporciona ningún valor de retorno o falta `return`, se devuelve `None`.

``` python
def bar(x):
    eclaraciones
    return

a = bar(4)      # a = None

# O
def foo(x):
    declaraciones  # Sin `return`

b = foo(4)      # b = None
```

#### Valores de retorno múltiples

Las funciones solo pueden devolver un valor. Sin embargo, una función puede devolver múltiples valores al devolverlos en una tupla.

``` python
def divide(a,b):
    q = a // b # Cociente
    r = a % b # Resto
    return q, r # Devuelve una tupla
```

Ejemplo de uso:

``` python
x, y = divide(37,5) # x = 7, y = 2

x = divide(37, 5) # x = (7, 2)
```

#### Ámbito de la variable

Los programas asignan valores a las variables.

``` python
x = valor # Variable global

def foo():
    y = valor # Variable local
```

Las asignaciones de variables ocurren fuera y dentro de las definiciones de funciones. Las variables definidas fuera son "globales". Las variables dentro de una función son "locales".

#### Variables locales

Las variables asignadas dentro de las funciones son privadas.

``` python
def read_portfolio(filename):
    portfolio = []
    for line in open(filename):
        fields = line.split(',')
        s = (fields[0], int(fields[1]), float(fields[2]))
        portfolio.append(s)
    return portfolio
```

En este ejemplo, `filename`, `portfolio`, `line`, `fields` y `s` son variables locales. Esas variables no se conservan ni se puede acceder a ellas después de la llamada a la función.

``` python
>>> stocks = read_portfolio('portfolio.csv')
>>> fields
Traceback (most recent call last):
File "<stdin>", line 1, in ?
NameError: name 'fields' is not defined
>>>
```

Las variables locales tampoco pueden entrar en conflicto con las variables que se encuentran en otro lugar.

#### Variables globales

Las funciones pueden acceder libremente a los valores de las variables globales definidas en el mismo archivo.

``` python
name = 'Dave'

def greeting():
    print('Hola', name)  # Uso de la variable global `name`
```

Sin embargo, las funciones no pueden modificar las variables globales:

``` python
name = 'Dave'

def spam():
  name = 'Guido'

spam()
print(name) # imprime 'Dave'
```

**Recuerde: todas las asignaciones en funciones son locales.**

#### Modificación de variables globales

Si debe modificar una variable global, debe declararla como tal.

``` python
name = 'Dave'

def spam():
    global name
    name = 'Guido' # Cambia el nombre global anterior
```

La declaración global debe aparecer antes de su uso y la variable correspondiente debe existir en el mismo archivo que la función. Habiendo visto esto, debes saber que se considera una mala forma de hacerlo. De hecho, intenta evitar el uso de "global" por completo si puedes. Si necesitas una función para modificar algún tipo de estado fuera de la función, es mejor usar una clase en su lugar (más sobre esto más adelante).

#### Pase de argumentos

Cuando llamas a una función, las variables de argumento son nombres que hacen referencia a los valores pasados. Estos valores NO son copias (ver [sección 2.7] ../02_Working_with_data/07_Objects.md)). Si se pasan tipos de datos mutables (por ejemplo, listas, diccionarios), se pueden modificar *in situ*.

``` python
def foo(items):
    items.append(42)    # Modifies the input object

a = [1, 2, 3]
foo(a)
print(a)           # [1, 2, 3, 42]
```

**Punto clave: Las funciones no reciben una copia de los argumentos de entrada.**

#### Reasignación vs. Modificación

Asegúrese de comprender la sutil diferencia entre modificar un valor y reasignar un nombre de variable.

``` python
def foo(items):
    items.append(42) # Modifica el objeto de entrada

a = [1, 2, 3]
foo(a)
print(a) # [1, 2, 3, 42]

# en lugar de

def bar(items):
    items = [4,5,6] # Cambia la variable `items` local para que apunte a un objeto diferente

b = [1, 2, 3]
bar(b)
print(b) # [1, 2, 3]
```

*Recordatorio: la asignación de variables nunca sobrescribe la memoria. El nombre simplemente está ligado a un nuevo valor.*

#### Ejercicios

Este conjunto de ejercicios te permite implementar lo que es, quizás, la parte más poderosa y difícil del curso. Hay muchos pasos y muchos conceptos de ejercicios anteriores se combinan a la vez. La solución final consta de tan solo unas 25 líneas de código, pero tómate tu tiempo y asegúrate de comprender cada parte.

Una parte central de tu programa `report.py` se centra en la lectura de archivos CSV. Por ejemplo, la función `read_portfolio()` lee un archivo que contiene filas de datos de cartera y la función `read_prices()` lee un archivo que contiene filas de datos de precios. En ambas funciones, hay muchos fragmentos "complicados" de bajo nivel y características similares. Por ejemplo, ambas abren un archivo y lo envuelven con el módulo `csv` y ambas convierten varios campos en nuevos tipos.

Si estuvieras haciendo mucho análisis de archivos de verdad, probablemente querrías limpiar algo de esto y hacerlo más general. Ese es nuestro objetivo.

Comienza este ejercicio abriendo el archivo llamado `Work/fileparse.py`. Aquí es donde haremos nuestro trabajo.

#### Ejercicio 3.3: Lectura de archivos CSV

Para comenzar, centrémonos en el problema de leer un archivo CSV en una lista de diccionarios. En el archivo `fileparse.py`, defina una función que se parezca a esto:

``` python
# fileparse.py
import csv

def parse_csv(filename):
    '''
    Analiza un archivo CSV en una lista de registros
    '''
    with open(filename) as f:
        rows = csv.reader(f)

        # Read the file headers
        headers = next(rows)
        records = []
        for row in rows:
            if not row:    # Omite filas sin datos
                continue
            record = dict(zip(headers, row))
            records.append(record)

    return records
```

Esta función lee un archivo CSV en una lista de diccionarios mientras oculta los detalles de apertura del archivo, lo envuelve con el módulo `csv`, ignora las líneas en blanco, etc.

Pruébelo:

Sugerencia: `python -i fileparse.py`.

``` python
>>> portfolio = parse_csv('Data/portfolio.csv')
>>> portfolio
[{'price': '32.20', 'name': 'AA', 'shares': '100'}, {'price': '91.10', 'name': 'IBM', 'shares': '50'}, {'price': '83.44', 'name': 'CAT', 'shares': '150'}, {'price': '51.23', 'name': 'MSFT', 'shares': '200'}, {'price': '40.37', 'name': 'GE', 'shares': '95'}, {'price': '65.10', 'name': 'MSFT', 'shares': '50'}, {'price': '70.44', 'name': 'IBM', 'shares': '100'}]
>>>
```

Esto es bueno, excepto que no se puede hacer ningún tipo de cálculo útil con los datos porque todo se representa como una cadena. Arreglaremos esto en breve, pero sigamos trabajando en ello.

#### Ejercicio 3.4: Creación de un selector de columnas

En muchos casos, solo interesan las columnas seleccionadas de un archivo CSV, no todos los datos. Modifique la función `parse_csv()` para que permita opcionalmente seleccionar columnas especificadas por el usuario de la siguiente manera:

``` python
>>> # Leer todos los datos
>>> portfolio = parse_csv('Data/portfolio.csv')
>>> portfolio
[{'price': '32.20', 'name': 'AA', 'shares': '100'}, {'price': '91.10', 'name': 'IBM', 'shares': '50'}, {'price': '83.44', 'name': 'CAT', 'shares': '150'}, {'price': '51.23', 'name': 'MSFT', 'shares': '200'}, {'price': '40.37', 'name': 'GE', 'shares': '95'}, {'price': '65.10', 'name': 'MSFT', 'shares': '50'}, {'price': '70.44', 'name': 'IBM', 'shares': '100'}]

>>> # Leer solo algunos de los datos
>>> shares_held = parse_csv('Data/portfolio.csv', select=['name','shares'])
>>> shares_held
[{'name': 'AA', 'shares': '100'}, {'name': 'IBM', 'shares': '50'}, {'name': 'CAT', 'shares': '150'}, {'name': 'MSFT', 'shares': '200'}, {'name': 'GE', 'shares': '95'}, {'name': 'MSFT', 'shares': '50'}, {'name': 'IBM', 'shares': '100'}]
>>>
```

En el [Ejercicio 2.23](../02_Working_with_data/06_List_comprehension.Rmd) se proporcionó un ejemplo de selector de columnas. Sin embargo, aquí se muestra una forma de hacerlo:

``` python
# fileparse.py
import csv

def parse_csv(filename, select=None):
    '''
    Analizar un archivo CSV con una lista de registros
    '''
    with open(filename) as f:
        rows = csv.reader(f)

        # Leer los encabezados del archivo
        headers = next(rows)

        # Si se proporcionó un selector de columnas, buscar los índices de las columnas especificadas
        # También se limita el conjunto de encabezados utilizados para los diccionarios resultantes
        if else:
            indices = []

        records = []
        for row in rows:
            if not row:    # Omite filas sin datos
                continue
            # Filtrar la fila si se seleccionaron columnas específicas
            if indices:
                row = [ row[index] for index in indices ]

            # Crear un dicciona
            record = dict(zip(headers, row))
            records.append(record)

    return records
```

Esta parte tiene varios puntos complicados. Probablemente, el más importante sea la asignación de las selecciones de columnas a los índices de filas. Por ejemplo, supongamos que el archivo de entrada tiene los siguientes encabezados:

``` python
>>> headers = ['name', 'date', 'time', 'shares', 'price']
>>>
```

Ahora, supongamos que las columnas seleccionadas fueran las siguientes:

``` python
>>> select = ['name', 'shares']
>>>
```

Para realizar la selección adecuada, debe asignar los nombres de las columnas seleccionadas a los índices de las columnas en el archivo. Esto es lo que hace este paso:

``` python
>>> indices = [headers.index(colname) for colname in select ]
>>> indices
[0, 3]
>>>
```

En otras palabras, 'name' es la columna 0 y 'shares\` es la columna 3. Cuando se lee una fila de datos del archivo, se utilizan los índices para filtrarla:

``` python
>>> row = ['AA', '6/11/2007', '9:50am', '100', '32.20' ]
>>> row = [ row[index] for index in indices ]
>>> row
['AA', '100']
>>>
```

#### Ejercicio 3.5: Realizar conversión de tipos

Modifique la función `parse_csv()` para que permita opcionalmente conversiones de tipo que se aplicarán a los datos devueltos. Por ejemplo:

``` python
>>> portfolio = parse_csv('Data/portfolio.csv', types=[str, int, float])
>>> portfolio
[{'price': 32.2, 'name': 'AA', 'shares': 100}, {'price': 91.1, 'name': 'IBM', 'shares': 50}, {'price': 83.44, 'name': 'CAT', 'shares': 150}, {'price': 51.23, 'name': 'MSFT', 'shares': 200}, {'price': 40.37, 'name': 'GE', 'shares': 95}, {'price': 65.1, 'name': 'MSFT', 'shares': 50}, {'price': 70.44, 'name': 'IBM', 'shares': 100}]

>>> shares_held = parse_csv('Data/portfolio.csv', select=['name', 'shares'], types=[str, int])
>>> shares_held
[{'name': 'AA', 'shares': 100}, {'name': 'IBM', 'shares': 50}, {'name': 'CAT', 'shares': 150}, {'name': 'MSFT', 'shares': 200}, {'name': 'GE', 'shares': 95}, {'name': 'MSFT', 'shares': 50}, {'name': 'IBM', 'shares': 100}]
>>>
```

Ya exploraste esto en [Ejercicio 2.24](../02_Working_with_data/07_Objects.Rmd).

Necesitará insertar el siguiente fragmento de código en su solución:

``` python
...
if types:
    row = [func(val) for func, val in zip(types, row) ]
...
```

#### Ejercicio 3.6: Trabajar sin encabezados

Algunos archivos CSV no incluyen ninguna información de encabezado. Por ejemplo, el archivo `prices.csv` tiene este aspecto:

``` csv
"AA",9.22
"AXP",24.85
"BA",44.85
"BAC",11.27
...
```

Modifique la función `parse_csv()` para que pueda trabajar con dichos archivos creando una lista de tuplas en su lugar. Por ejemplo:

``` python
>>> prices = parse_csv('Data/prices.csv', types=[str,float], has_headers=False)
>>> prices
[('AA', 9.22), ('AXP', 24.85), ('BA', 44.85), ('BAC', 11.27), ('C', 3.72), ('CAT', 35.46), ('CVX', 66.67), ('DD', 28.47), ('DIS', 24.22), ('GE', 13.48), ('GM', 0.75), ('HD', 23.16), ('HPQ', 34.35), ('IBM', 106.28), ('INTC', 15.72), ('JNJ', 55.16), ('JPM', 36.9), ('KFT', 26.11), ('KO', 49.16), ('MCD', 58.99), ('MMM', 57.1), ('MRK', 27.58), ('MSFT', 20.89), ('PFE', 15.19), ('PG', 51.94), ('T', 24.79), ('UTX', 52.61), ('VZ', 29.26), ('WMT', 49.74), ('XOM', 69.35)]
>>>
```

Para realizar este cambio, deberá modificar el código de modo que la primera línea de datos No se interpreta como una línea de encabezado. Además, deberá asegurarse de no crear diccionarios, ya que ya no hay nombres de columnas para usar como claves.

#### Ejercicio 3.7: Elegir un delimitador de columna diferente

Aunque los archivos CSV son bastante comunes, también es posible encontrar un archivo que utilice un separador de columnas diferente, como una tabulación o un espacio. Por ejemplo, el archivo `Data/portfolio.dat` tiene este aspecto:

``` csv
name shares price
"AA" 100 32.20
"IBM" 50 91.10
"CAT" 150 83.44
"MSFT" 200 51.23
"GE" 95 40.37
"MSFT" 50 65.10
"IBM" 100 70.44
```

La función `csv.reader()` permite indicar un delimitador de columna diferente de la siguiente manera:

``` python
rows = csv.reader(f, delimiter=' ')
`` `

Modifique su función `parse_csv()` para que también permita cambiar el delimitador.

Por ejemplo:

```python
>>> portfolio = parse_csv('Data/portfolio.dat', types=[str, int, float], delimiter=' ')
>>> portfolio
[{'price': '32.20', 'name': 'AA', 'shares': '100'}, {'price': '91.10', 'name': 'IBM', 'shares': '50'}, {'price': '83.44', 'name': 'CAT', 'shares': '150'}, {'price': '51.23', 'name': 'MSFT', 'shares': '200'}, {'price': '40.37', 'name': 'GE', 'shares': '95'}, {'price': '65.10', 'name': 'MSFT', 'shares': '50'}, {'price': '70.44', 'name': 'IBM', 'shares': '100'}]
>>>
```

#### Comentario

Si has llegado hasta aquí, has creado una bonita función de biblioteca que es realmente útil. Puedes usarla para analizar archivos CSV arbitrarios, seleccionar columnas de interés, realizar conversiones de tipos, sin tener que preocuparte demasiado por el funcionamiento interno de los archivos o el módulo `csv`.

[Contenido](../Contents.Rmd) \| [Anterior (3.1 Funciones y escritura de scripts)](01_Script.Rmd) \| [Próximo (3.3 Comprobación de errores)](03_Error_checking.Rmd)
