---
title: "04_Modules"
output: html_document
---

[Contenido](../Contents.Rmd) \| [Anterior (3.3 Comprobación de errores)](03_Error_checking.Rmd) \| [Próximo (3.5 Módulo principal)](05_Main_module.Rmd)

### 3.4 Módulos

Esta sección presenta el concepto de módulos y el trabajo con funciones que abarcan varios archivos.

#### Módulos e importación

Cualquier archivo fuente de Python es un módulo.

``` python
# foo.py
def grok(a):
    ...
def spam(b):
    ...
```

La declaración `import` carga y *ejecuta* un módulo.

``` python
# program.py
import foo

a = foo.grok(2)
b = foo.spam('Hola')
...
```

#### Espacio de nombres

Un módulo es una colección de valores nombrados y a veces se dice que es un *espacio de nombres o namespace*. Los nombres son todas las variables y funciones globales definidas en el archivo fuente. Después de la importación, el nombre del módulo se utiliza como prefijo. De ahí el *espacio de nombres*.

``` python
import foo

a = foo.grok(2)
b = foo.spam('Hola')
...
```

El nombre del módulo está directamente vinculado al nombre del archivo (foo -\> foo.py).

#### Definiciones globales

Todo lo definido en el ámbito *global* es lo que llena el espacio de nombres del módulo. Considere dos módulos que definen la misma variable `x`.

``` python
# foo.py
x = 42
def grok(a):
    ...
```

``` python
# bar.py
x = 37
def spam(a):
    ...
```

En este caso, las definiciones de `x` se refieren a diferentes variables. Una es `foo.x` y la otra es `bar.x`. Diferentes módulos pueden usar los mismos nombres y esos nombres no entrarán en conflicto entre sí.

**Los módulos están aislados.**

#### Módulos como entornos

Los módulos forman un entorno envolvente para todo el código definido en su interior.

``` python
# foo.py
x = 42

def grok(a):
    print(x)
```

Las variables *globales* siempre están vinculadas al módulo envolvente (mismo archivo). Cada archivo fuente es su propio pequeño universo.

#### Ejecución de módulo

Cuando se importa un módulo, *todas las instrucciones del módulo se ejecutan* una tras otra hasta llegar al final del archivo. El contenido del espacio de nombres del módulo son todos los nombres *globales* que todavía están definidos al final del proceso de ejecución. Si hay instrucciones de script que realizan tareas en el ámbito global (imprimir, crear archivos, etc.), verá que se ejecutan durante la importación.

#### Instrucción `import as`

Puede cambiar el nombre de un módulo mientras lo importa:

``` python
import math as m
def rectangular(r, theta):
    x = r * m.cos(theta)
    y = r * m.sin(theta)
    return x, y
```

Funciona igual que una importación normal. Simplemente cambia el nombre del módulo en ese archivo.

#### Importación de módulo `from`

Esto selecciona símbolos seleccionados de un módulo y los pone a disposición localmente.

``` python
from math import sin, cos

def rectangular(r, theta):
    x = r * cos(theta)
    y = r * sin(theta)
    return x, y
```

Esto permite que se utilicen partes de un módulo sin tener que escribir el prefijo del módulo. Es útil para nombres de uso frecuente.

#### Comentarios sobre la importación

Las variaciones en la importación *no* cambian la forma en que funcionan los módulos.

``` python
import math
# versus
import math as m
# versus
from math import cos, sin
...
```

Específicamente, `import` siempre ejecuta el archivo *completo* y los módulos siguen siendo entornos aislados.

La declaración `import module as` solo cambia el nombre localmente. La declaración `from math import cos, sin` todavía carga el módulo matemático completo detrás de escena. Simplemente copia los nombres `cos` y `sin` del módulo al espacio local después de que finaliza.

#### Carga de módulos

Cada módulo se carga y se ejecuta solo *una vez*. *Nota: Las importaciones repetidas solo devuelven una referencia al módulo cargado previamente.*

`sys.modules` es un diccionario de todos los módulos cargados.

``` python
>>> import sys
>>> sys.modules.keys()
['copy_reg', '__main__', 'site', '__builtin__', 'encodings', 'encodings.encodings', 'posixpath', ...]
>>>
```

**Precaución:** Surge una confusión común si repite una declaración `import` después de cambiar el código fuente de un módulo. Debido a la caché de módulos `sys.modules`, las importaciones repetidas siempre devuelven el módulo cargado previamente, incluso si se realizó un cambio. La forma más segura de cargar código modificado en Python es salir y reiniciar el intérprete.

#### Localización de módulos

Python consulta una lista de rutas (sys.path) cuando busca módulos.

``` python
>>> import sys
>>> sys.path
[
'',
'/usr/local/lib/python36/python36.zip',
'/usr/local/lib/python36',
...
]
```

El directorio de trabajo actual suele ser el primero.

#### Ruta de búsqueda de módulos

Como se indicó, `sys.path` contiene las rutas de búsqueda. Puede ajustarlas manualmente si es necesario.

``` python
import sys
sys.path.append('/project/foo/pyfiles')
```

Las rutas también se pueden agregar a través de variables de entorno.

``` shell
bash % env PYTHONPATH=/project/foo/pyfiles python
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', 'C:\\Program Files\\Git\\project\\foo\\pyfiles', ...]
```

Como regla general, no debería ser necesario ajustar manualmente la ruta de búsqueda del módulo. Sin embargo, a veces surge si intenta importar código Python que se encuentra en una ubicación inusual o que no es fácilmente accesible desde el directorio de trabajo actual.

#### Ejercicios

Para este ejercicio que involucra módulos, es de vital importancia asegurarse de que está ejecutando Python en un entorno adecuado. Los módulos a menudo presentan a los nuevos programadores problemas relacionados con el directorio de trabajo actual o con la configuración de la ruta de Python. Para este curso, se supone que está escribiendo todo su código en el directorio `Work/`. Para obtener mejores resultados, debe asegurarse de que también está en ese directorio cuando inicia el intérprete. Si no es así, debe asegurarse de que `practical-python/Work` se agregue a `sys.path`.

##### Ejercicio 3.11: Importaciones de módulos

En la sección 3, creamos una función de propósito general `parse_csv()` para analizar el contenido de los archivos de datos CSV.

Ahora, vamos a ver cómo usar esa función en otros programas. Primero, comienza en una nueva ventana de shell. Navega hasta la carpeta donde tienes todos tus archivos. Vamos a importarlos.

Inicia el modo interactivo de Python.

``` shell
bash % $ python
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Una vez que hayas hecho eso, intenta importar algunos de los programas que escribiste anteriormente. Deberías ver su salida exactamente como antes. Solo para enfatizar, importar un módulo ejecuta su código.

``` python
>>> import bounce
... mira el resultado ...
>>> import mortgage
... mira el resultado ...
>>> import report
... mira el resultado ...
>>>
```

Si nada de esto funciona, probablemente estés ejecutando Python en el directorio incorrecto. Ahora, intenta importar tu módulo `fileparse` y obtener ayuda al respecto.

``` python
>>> import fileparse
>>> help(fileparse)
... mira el resultado...
>>> dir(fileparse)
... mira el resultado...
>>>
```

Intenta usar el módulo para leer algunos datos:

``` python
>>> portfolio = fileparse.parse_csv('Data/portfolio.csv',select=['name','shares','price'], types=[str,int,float])
>>> portfolio
... mira el resultado...
>>> pricelist = fileparse.parse_csv('Data/prices.csv',types=[str,float], has_headers=False)
>>> pricelist
... mira el resultado...
>>> prices = dict(pricelist)
>>> prices
... mira el resultado...
>>> prices['IBM']
106.11
>>>
```

Intenta importar una función de modo que no necesites incluir el nombre del módulo:

``` python
>>> from fileparse import parse_csv
>>> portfolio = parse_csv('Data/portfolio.csv', select=['name','shares','price'], types=[str,int,float])
>>> portfolio
... mira el resultado...
>>>
```

##### Ejercicio 3.12: Uso del módulo de la biblioteca

En la sección 2, escribiste un programa `report.py` que produjo un informe de acciones como este:

```         
Nombre Acciones Precio Cambio
---------- ---------- ---------- ----------
AA 100 9.22 -22.98
IBM 50 106.28 15.18
CAT 150 35,46 -47,98
MSFT 200 20,89 -30,34
GE 95 13,48 -26,89
MSFT 50 20,89 -44,21
IBM 100 106,28 35,84
```

Tome ese programa y modifíquelo de modo que todo el procesamiento del archivo de entrada se realice utilizando funciones en su módulo `fileparse`. Para ello, importe `fileparse` como módulo y cambie las funciones `read_portfolio()` y `read_prices()` para utilizar la función `parse_csv()`.

Use el modo interactivo al comienzo de este ejercicio como guía. Después, debería obtener exactamente el mismo resultado que antes.

##### Ejercicio 3.13: Se dejó en blanco intencionalmente (omitir)

##### Ejercicio 3.14: Uso de más importaciones de bibliotecas

En la sección 1, escribió un programa `pcost.py` que lee una cartera y calcula su costo.

``` python
>>> import pcost
>>> pcost.portfolio_cost('Data/portfolio.csv')
44671.15
>>>
```

Modifique el archivo `pcost.py` para que use la función `report.read_portfolio()`.

#### Comentario

Cuando haya terminado con este ejercicio, debería tener tres programas. `fileparse.py` que contiene una función `parse_csv()` de propósito general. `report.py` que produce un informe atractivo, pero también contiene las funciones read_portfolio()`y`read_prices()`. Y finalmente,`pcost.py`que calcula el costo de la cartera, pero hace uso de la función`read_portfolio()`escrita para el programa`report.py\`.

[Contenido](../../Contents.Rmd) \| [Anterior (3.3 Comprobación de errores)](3.3%20Error%20Checking.Rmd) \| [Próximo (3.5 Módulo principal)](05_Main_module.Rmd)
